name: CI/CD Pipeline

on:
  push:
    branches:
      - master # You can specify the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_extensions: bcmath intl gd zip
      - run: vendor/bin/phpunit
      - run: |
          cd /var/www/akaunting
          git pull origin master
          composer install
          npm install
          chown -R www-data:www-data ../akaunting