name: CI/CD Pipeline

on:
  push:
    branches:
      - master # You can specify the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check Out Code
      - uses: actions/checkout@v3

      # Composer to Install Dependencies with Various Extensions
      # - uses: php-actions/composer@v6
      #   with:
      #     php_extensions: bcmath intl gd zip

      # Install Dependencies
      # - run: npm install
      # - run: composer install

      # Run PHP Unit Tests
      # - run: vendor/bin/phpunit

      # Deploy The Project
      # cd /var/www/akaunting
      # - name: Deploy Project
      #   run: |
      #     git pull origin master
      #     composer install
      #     npm install
      #     chown -R www-data:www-data ../akaunting

      - name: Capture Build History
        run: |
          echo "Build started: $(date)" >> reports//build-history.txt
          echo "Commit: $(git rev-parse HEAD)" >> reports//build-history.txt
          echo "Branch: $(git rev-parse --abbrev-ref HEAD)" >> reports//build-history.txt

      # Generate Reports
        # History of the Build
      - name: Upload Build History Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-history
          path: reports/build-history.txt

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: Upload Build History Artifact  # Replace with the actual artifact name
          path: reports/build-history-test.txt
