name: CI/CD Pipeline

on:
  push:
    branches:
      - master # You can specify the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest # Specify the runner environment
    
    steps:
    # Debug
    # - name: Verification
    #   run: echo "Verification Success" # This action verifies that ci.yml is working

    # - name: Install Composer
    #   run: composer install

    - name: PHP Unit Tests
      uses: php-actions/phpunit@v3
      with:
        configuration: "phpunit.xml"
        memory_limit: "256M"

    - name: Checkout Code
      uses: actions/checkout@v2 # This action checks out the repository's code

    - name: Deploy Project
      run: | # This action deploys the project on the server
        cd /var/www/akaunting
        git pull origin master 
        composer install
        npm install
        chown -R www-data:www-data ../akaunting