name: CI/CD Pipeline

on:
  push:
    branches:
      - master # You can specify the branch you want to trigger the workflow on

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - uses: php-actions/composer@v6
        with:
          php_extensions: bcmath intl gd zip
      - run: echo "Composer dependencies have been installed"
      - run: vendor/bin/phpunit

    #- name: Checkout Code
    #  uses: actions/checkout@v2 # This action checks out the repository's code
    
    #- name: Deploy Project
    #  run: | # This action deploys the project on the server
    #    cd /var/www/akaunting
    #    git pull origin master 
    #    composer install
    #    npm install
    #    chown -R www-data:www-data ../akaunting