name: CI/CD Pipeline

on:
  push:
    branches:
      - master # You can specify the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check Out Code
      - uses: actions/checkout@v3

      # Composer to Install Dependencies with Various Extensions
      - uses: php-actions/composer@v6
        with:
          php_extensions: bcmath intl gd zip

      # Install Dependencies
      - run: npm install
      - run: composer install

      # Run PHP Unit Tests
      # - run: vendor/bin/phpunit

      # Deploy The Project
      # cd /var/www/akaunting
      - name: Deploy Project
        run: |
          git pull origin master
          composer install
          npm install
          chown -R www-data:www-data ../akaunting

      # Generate Reports
        # History of the Build
      - name: Archive Report
        uses: actions/upload-artifact@v2
        with:
          name: build-report
          path: .github/workflows/reports